version: 0.2

phases:
  install:
    commands:
      - echo "Install Phase"
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
  build:
    commands:
      - echo "Build Phase"
      - mkdir dist
      - cp index.html ./dist/index.html
      - echo "build logs" > logs.txt
  post_build:
    commands:
      - echo "Post Build Phase"
      - |
        if [ $CODEBUILD_WEBHOOK_TRIGGER = "branch/main" ]; then
          aws s3 cp ./dist/index.html s3://kennet-codebuild
        else
          echo "Skipping S3 asset uploading."
        fi

artifacts:
  files:
    - logs.txt
